config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { sessions: 'users/sessions' }
  root to: "rubberducks#index"
  resources :rubber_ducks
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
  get "/profile", to: "pages#profile", as: :profile

  resources :users do
    resources :rubberducks
  end

  resources :rubberducks, only: [:index, :show] do
    resources :bookings, only: [:new, :create, :index]
  end

  resources :rubberducks do
    get 'calculate_price', on: :member
  end
  resources :bookings, only: [:destroy, :edit, :update]
end

app/models/user.rb
require 'bcrypt'

class User < ApplicationRecord
  has_many :rubberducks, dependent: :destroy
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
        :recoverable, :rememberable
  has_many :bookings

  def average_rubberduck_rating
    return 0 if rubberducks.empty?
    rubberducks.average(:rating).to_f.round(2)
  end
end
# comment

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  #

  def destroy
    # super do |resource|
    #   redirect_to rubberducks_path, notice: "Signed out successfully."
    #   return
    # end
    super
    reset_session
  end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: :show

  def index
    @user = User.all
    @rubberducks = Rubberduck.all
  end

  def show
    @rubberducks = Rubberduck.all
    @bookings = Booking.all
  end

  private

  def set_user
    @user = User.find(params[:id])
  rescue ActiveRecord::RecordNotFound
    redirect_to users_path, alert: 'User not found'
  end
end

app/views/users/_user_details.html.erb
<div class="container mt-4">
  <div class="row d-flex">

    <div class="col-md-4 stats">
      <div class="user-details detail">
        <ul>
          <li><strong><%= @user.rubberducks.count %></strong> listed rubberducks</li>
          <li><%= @user.average_rubberduck_rating %> <i class="fas fa-star fa-lg"></i> Rating </li>
          <li>Verified User <i class="fas fa-check fa-lg"></i></li>
        </ul>
      </div>
      <% if @user == current_user %>
        <div class="detail">
          <ul>
            <li><strong><%= @user.bookings.count %></strong> current bookings</li>
            <li><%= link_to "Your booking details", profile_path(current_user), style: "text-decoration: none" %></li>
          </ul>
        </div>
      <% end %>
    </div>

    <div class="col-md-8 about-me d-flex flex-column">
      <div>
        <h2><strong>About Me</strong></h2>
        <% if @user.description.present? %>
          <p><%= @user.description %></p>
        <% else %>
          <p><em>No description provided yet.</em></p>
        <% end %>
      </div>
      <div class="detail mt-auto">
        <% favourite_rubberduck = @user.rubberducks.sample %>
        <ul id="fav-duck">
          <li><span id="fav-duck-name">Favourite rubberduck </span> : <%= link_to "#{favourite_rubberduck.name}", rubberduck_path(favourite_rubberduck), style: "text-decoration: none" %></li>
        </ul>
      <div>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<% if user_signed_in? %>
  <% if current_user == @user %>
    <h1>Your Profile</h1>
  <% else %>
    <h1><%= @user.name %>'s Profile</p>
  <% end %>

  <%= render partial: "users/user_details" %>

  <div class="boundary"></div>

  <% if @user.rubberducks.any? %>
    <% if current_user == @user %>
      <h2 class="title"><strong>Your listed rubberducks</strong></h2>
    <% else %>
      <h2 class="title"><strong><%= @user.name %>'s listed rubberducks</strong></h2>
    <% end %>
  <% end %>
<% else %>
  <h1 class="title">Welcome to <%= @user.name %>'s Profile</h1>
  <% if @user.rubberducks.any? %>
    <h2 class="title"><strong><%= @user.name %>'s listed rubberducks</strong></h2>
  <% end %>
<% end %>

<% if @user.rubberducks.any? %>
  <div class="duck-container">
    <ul class="duck-list" style="display: grid; grid-template-columns: repeat(auto-fill, minmax(200px, 1fr)); gap: 20px;">
      <% @user.rubberducks.each do |rubberduck| %>
        <li>
          <% if user_signed_in? %>
            <%= render "shared/rubber_duck_card", rubberduck: rubberduck %>
          <% else %>
            <%= render "shared/rubber_duck_card", rubberduck: rubberduck %>
          <% end %>
        </li>
      <% end %>
    </ul>
  </div>
<% else %>
  <p>No rubberducks available.</p>
<% end %>