config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { sessions: 'users/sessions' }
  root to: "rubberducks#index"
  resources :rubber_ducks
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
  get "/profile", to: "pages#profile", as: :profile

  resources :users do
    resources :rubberducks
  end

  resources :rubberducks, only: [:index, :show] do
    resources :bookings, only: [:new, :create, :index]
  end

  resources :rubberducks do
    get 'calculate_price', on: :member
  end
  resources :bookings, only: [:destroy, :edit, :update]
end

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<div>
<p>Find me in app/views/pages/home.html.erb</p>
  <%= link_to "Small Button", root_path, class: "button small color:" %>
  <%= link_to "Default Button", root_path, class: "button" %>
  <%= link_to "Large Button", root_path, class: "button large" %>
  <%= link_to "Primary Button", root_path, class: "button primary" %>
  <%= link_to "Danger Button", root_path, class: "button danger" %>
</div>

app/views/pages/profile.html.erb
<h1>Bookings Overview</h1>
<h2>Username: <%= current_user.name %></h2>
<br>
<% if @bookings.any? %>  <!-- Check if there are any bookings -->
  <h3><strong>Your bookings</strong></h3>
  <div class="boundary"></div>
  <div class="container">
  <div class="row d-flex">
  <% @bookings.each do |booking| %>
    <div class="col-auto stats">
    <div class="detail book">
    <!-- Calculating the length of the booking -->
    <% total_nights = (booking.end_date - booking.start_date).to_i %>
    <!-- Calculate the total price -->
    <% total_price = total_nights * booking.rubberduck.price %>

    <p><strong>Rubberduck name</strong>: <%= link_to "#{booking.rubberduck.name}", rubberduck_path(booking.rubberduck), style: "text-decoration: none" %></p>
    <p><strong>Start Date</strong>: <%= booking.start_date %></p>
    <p><strong>End Date</strong>: <%= booking.end_date %></p>
    <p><strong>Booked for</strong>: <%= total_nights %> nights</p>
    <p><strong>Total price</strong>: $<%= total_price %></p>

    <!-- Action buttons for Delete and Edit -->
    <%= link_to "Delete", booking_path(booking), data: { turbo_method: :delete, turbo_confirm: "Are you sure?" }, class: "btn btn-danger" %>
    <%= link_to "Edit Booking", edit_booking_path(booking), class: "btn btn-warning" %>
    <br><br>
    </div>
    </div>
  <% end %>
  </div>
  </div>
<% else %>
  <h3>You currently have no active bookings</h3>
<% end %>